### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [hanjoongcho/aaf-easydiary#212]
ref: https://monitor.f-droid.org/builds/log/me.blog.korn123.easydiary/294#site-footer

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/718e73069a37a140ad6673d507567490743068a2

**Comment by licaon-kter** [comment]
Still failing: https://monitor.f-droid.org/builds/log/me.blog.korn123.easydiary/295#site-footer

**Comment by hanjoongcho** [comment]
Hi~ @licaon-kter 
It was processed as follows.

- https://github.com/hanjoongcho/aaf-easydiary/commit/14d01eca607fb676ac22cac83eabce00cee81ba0
- https://github.com/hanjoongcho/aaf-easydiary/commit/360198768f0b2ee2b11df0d9db96b200d72786dd

**Comment by licaon-kter** [comment]
The thign is that [you publish](https://github.com/hanjoongcho/aaf-easydiary/tags) `-fdroid` suffixed tags... but F-Droid is not instructed to use those: https://gitlab.com/fdroid/fdroiddata/-/blob/cbd6a01d28edf89942921a31c87922b674eb2e92/metadata/me.blog.korn123.easydiary.yml#L839

Buuut.. funny enough even the non-fdroid tagged release appear to build fine: https://f-droid.org/packages/me.blog.korn123.easydiary/

There was a change of plans?

**Comment by hanjoongcho** [comment]
@licaon-kter 
The googleplay version and f-droid version system are exactly the same.
Only the build options are different. (In the case of f-droid build, the function using the gms library is disabled.)
The reason f-droid suffix was added last time is that the distribution of f-droid is dependent on tagging, so suffix is attached to mean that only f-droid is distributed without distribution of the google play version.

v1.4.295.202304180: googleplay & f-droid distribution
v1.4.296.202304210-fdroid: f-droid distribution
v1.4.297.202304260: googleplay & f-droid distribution

**Comment by licaon-kter** [comment]
I did not understand, but if it works, mmmkay,

**Comment by licaon-kter** [comment]
and again: https://gitlab.com/fdroid/fdroiddata/-/jobs/6244150408#L1045

ref: https://github.com/hanjoongcho/aaf-easydiary/blob/v1.4.305.202402230/app/src/main/java/me/blog/korn123/easydiary/helper/BaseAlarmWorkExecutor.kt#L4-L10 these need to be moved to `gms`

**Comment by hanjoongcho** [comment]
@licaon-kter 
https://github.com/hanjoongcho/aaf-easydiary/tree/v1.4.335.202510020

Yes, you can mark the version where the issue is resolved with a tag, independent of any branch.

**Comment by licaon-kter** [comment]
still fails :( https://gitlab.com/fdroid/fdroiddata/-/jobs/11574179892#L654

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/11576820963#L647 nope

can you test locally and apply these 2 lines first?
```
$ sed -i -e '/maven.pkg.jetbrains.space/d' settings.gradle
$ sed -i -e '/play-services-auth/d' -e '/review/d' -e '/google-api/d' -e '/google-http-client/d' app/build.gradle
```
so you don't have to wait for our CI

maybe our sed is too aggressive?

**Comment by hanjoongcho** [comment]
@licaon-kter 
When building the FOSS version, GMS libraries are excluded.
https://github.com/hanjoongcho/aaf-easydiary/blob/develop/app/build.gradle#L144-L151

I tested it locally, and building with JDK 21 in the current state didn’t cause any issues.

**Comment by licaon-kter** [comment]
Our scanner is a hammer not a scalpel :) we need to carve the entries so they are not detected

**Comment by licaon-kter** [comment]
You don't need to do any extra stuff, we do it in the recipe, but would be helpful to understand if that's the issue.
