### ISSUE TITLE
App crashes when I click on 'diary postcard' option 

### ISSUE THREAD

**Issue by chrisbarth01** [hanjoongcho/aaf-easydiary#55]
**Expected behavior**
- I expected the 'Dairy postcard' option to open when I click on it 

**Actual behavior**
-  Whenever I click on the 'Dairy postcard' option, the app crashes. 

**How to reproduce**
- Download and install the latest version of the Easy dairy application 
- Launch the application  
- Click on the three vertically arranged dots at the top right corner of the screen 
- Click on the 'Dairy postcard'
- See error 

---

- App version: 1.4.75
- Device: Gionee f100s 
- Operating system: android version 6.0

---

**Recording of the bug**
- https://youtu.be/G67lsx61e_k

**Comment by chrisbarth01** [comment]
Hello @hanjoongcho, can you please do something about this issue?

**Comment by hanjoongcho** [comment]
Hello @chrisbarth01
The error report was well reviewed.

Unfortunately, the error contents are well organized, but there is no log at the time of the error, so I have not yet figured out the exact cause.
In case of an application downloaded from Google Play, I can check the error report if an abnormal termination occurs.

Please feel free to reply to the following information. 😃

Q1) Where did you download the application?

Q2) Is the problem device an emulator? Or is it a real device?

Q3) Do you have the same problem when attaching photos to a diary?

**Comment by chrisbarth01** [comment]
Thanks for you reply.

I downloaded the application from apkpure but the exact version(v 1.4.75_gms) on Google Play 
It is a real device and I don't face this kind of photo issue on my phone
Yes, when I try adding a photo to a diary, it won't be added(though the app doesn't crash at that point)....... 

I wish I could generate a logcat but it's unfortunate that I don't have a PC yet. I hope I gave you enough answers to know the exact cause.

**Comment by hanjoongcho** [comment]
Based on the information I have identified so far, I will look into the cause.
I will give you feedback as soon as find a reason.

**Comment by chrisbarth01** [comment]
OK, thanks.

**Comment by hanjoongcho** [comment]
@chrisbarth01 I suspect there was a problem reading or writing device storage, but I can not find any suspicious parts. 😥

The folders used by 'Easy Diary' are as follows. Can you check if there are folders and data?
01. /AAFactory/EasyDiary/Fonts
    -> Q1> Is there a folder? 
02. /AAFactory/EasyDiary/Photos
    -> Folder where photos are saved when attaching photos to diary  
    -> Q2> Is there a folder? 
    -> Q3> Does adding data to a folder attach photos to a diary?
03. /AAFactory/EasyDiary/Postcards
    -> When a postcard is created with a diary, the folder where the card is stored  
    -> Q4> Is there a folder? 
    -> Q5> Is the data added to the folder when the diary post card is created?

**Comment by chrisbarth01** [comment]
Well..... It's confusing. But I may try it out on a different device to confirm. I wish I could do a catalog (which I can't). Thanks for looking into this issue.

**Comment by jubreal** [comment]
Go to the app settings and grant storage permissions to the app. I think it should fix it.

**Comment by chrisbarth01** [comment]
Hello @hanjoongcho 
Is it this bug I reported that you just fixed in the latest release?

**Comment by hanjoongcho** [comment]
Hello @chrisbarth01 
Unfortunately, the issue you reported is not resolved. :(
I do not seem to be able to resolve the issue you're reporting because the issue is not replayed on my test equipment.

**Comment by jubreal** [comment]
@chrisbarth01 I couldn't also reproduce the bug on same test environment. I believe you didn't grant the necessary permissions to the app on your device and that is what is triggering the crash. 
Go to your device settings, go to apps, select this app, click on permissions and enable all permissions requested.  Let me know the result of this.

**Comment by chrisbarth01** [comment]
Nope at @jubreal, the app as I went to my system manager doesn't require storage.... It doesn't require the storage permission
